import { OnboardingStep } from './types';

export const INTELLIGENT_STEPS: OnboardingStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to SpectrumCosmo! 🎉',
    description: 'Your ultimate destination for anime-inspired merchandise, apparel, and collectibles. Let\'s take a quick tour to help you get started!',
    target: 'body',
    placement: 'center',
    isActive: true,
    order: 0,
    deviceType: 'both',
    condition: { always: true },
  },
  {
    id: 'navigation',
    title: 'Navigate with Ease',
    description: 'Find your way around! Use the navigation bar to browse categories, search for products, and access your account.',
    target: 'header',
    placement: 'bottom',
    isActive: true,
    order: 1,
    deviceType: 'both',
    condition: { always: true },
    fallbackSelector: 'nav',
  },
  {
    id: 'search',
    title: 'Find What You Love',
    description: 'Click the search icon to find specific products, characters, or series. Our smart search helps you discover exactly what you\'re looking for.',
    target: 'button[aria-label="Search"]',
    placement: 'bottom',
    isActive: true,
    order: 2,
    deviceType: 'both',
    condition: { pathname: ['/', '/products'] },
    fallbackSelector: 'input[type="text"]',
  },
  {
    id: 'categories',
    title: 'Browse by Category',
    description: 'Explore our curated collections! From anime apparel to collectibles, find products that match your fandom.',
    target: '[data-onboarding="categories"]',
    placement: 'top',
    isActive: true,
    order: 3,
    deviceType: 'both',
    condition: { pathname: ['/'] },
    navigateTo: '/',
    scrollTo: true,
    fallbackSelector: '.grid',
  },
  {
    id: 'products',
    title: 'Discover Products',
    description: 'Browse our full collection of anime merchandise. Click on any product to view details, pricing, and available variants.',
    target: '[data-onboarding="product-grid"]',
    placement: 'top',
    isActive: true,
    order: 4,
    deviceType: 'both',
    condition: { pathname: ['/products'] },
    navigateTo: '/products',
    scrollTo: true,
    fallbackSelector: '.grid',
  },
  {
    id: 'wishlist',
    title: 'Save for Later ❤️',
    description: 'Found something you love? Click the heart icon to add it to your wishlist. You can access your wishlist anytime from your account.',
    target: '[data-onboarding="wishlist"]',
    placement: 'left',
    isActive: true,
    order: 5,
    deviceType: 'both',
    condition: { pathname: ['/products', '/products/[id]'] },
    contextTargets: {
      '/products': '[data-onboarding="wishlist-grid"]',
      '/products/[id]': '[data-onboarding="wishlist-detail"]',
    },
    fallbackSelector: 'button[aria-label*="wishlist"]',
  },
  {
    id: 'cart',
    title: 'Your Shopping Cart',
    description: 'Review your selected items, adjust quantities, and proceed to checkout. Your cart saves everything until you\'re ready to buy.',
    target: '[data-onboarding="cart"]',
    placement: 'left',
    isActive: true,
    order: 6,
    deviceType: 'both',
    condition: { pathname: ['/cart'] },
    navigateTo: '/cart',
    fallbackSelector: 'button[aria-label="Cart"]',
  },
  {
    id: 'account',
    title: 'Your Account Hub',
    description: 'Manage your orders, saved addresses, profile information, and preferences all in one place.',
    target: '[data-onboarding="account"]',
    placement: 'bottom',
    isActive: true,
    order: 7,
    deviceType: 'both',
    condition: { isLoggedIn: true, pathname: ['/account'] },
    navigateTo: '/account',
    fallbackSelector: '[data-account]',
  },
  {
    id: 'account-guest',
    title: 'Create Your Account',
    description: 'Create an account to track orders, save wishlist items, and get personalized recommendations.',
    target: '[data-onboarding="signup"]',
    placement: 'bottom',
    isActive: true,
    order: 7,
    deviceType: 'both',
    condition: { isLoggedIn: false },
    navigateTo: '/signup',
    fallbackSelector: 'a[href="/signup"]',
  },
  {
    id: 'checkout',
    title: 'Secure Checkout',
    description: 'Complete your purchase with our secure checkout. Review your order, enter delivery details, and choose your payment method.',
    target: '[data-onboarding="checkout"]',
    placement: 'top',
    isActive: true,
    order: 8,
    deviceType: 'both',
    condition: { pathname: ['/checkout'] },
    navigateTo: '/checkout',
    fallbackSelector: '.checkout',
  },
  {
    id: 'finish',
    title: 'You\'re All Set! 🚀',
    description: 'You\'re ready to explore SpectrumCosmo! Start shopping, discover new collections, and join our community of anime fans.',
    target: 'body',
    placement: 'center',
    isActive: true,
    order: 9,
    deviceType: 'both',
    condition: { always: true },
  },
];

export const MOBILE_STEPS: OnboardingStep[] = INTELLIGENT_STEPS.map(step => ({
  ...step,
  placement: step.placement === 'right' ? 'bottom' : 
              step.placement === 'left' ? 'bottom' : 
              step.placement === 'top' ? 'bottom' : 
              step.placement,
}));
