import { OnboardingStep } from './types';

export const DEFAULT_STEPS: OnboardingStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to SpectrumCosmo! 🎉',
    description: 'Your ultimate destination for anime-inspired merchandise, apparel, and collectibles. Let\'s take a quick tour to help you get started!',
    target: 'body',
    placement: 'center',
    isActive: true,
    order: 0,
    deviceType: 'both',
  },
  {
    id: 'navigation',
    title: 'Navigate with Ease',
    description: 'Find your way around! Use the navigation bar to browse categories, search for products, and access your account.',
    target: 'nav, header, .navbar, [role="navigation"]',
    placement: 'bottom',
    isActive: true,
    order: 1,
    deviceType: 'both',
  },
  {
    id: 'search',
    title: 'Find What You Love',
    description: 'Search for specific products, characters, or series. Our smart search helps you discover exactly what you\'re looking for.',
    target: 'input[type="search"], [role="search"], .search-input',
    placement: 'bottom',
    isActive: true,
    order: 2,
    deviceType: 'both',
  },
  {
    id: 'categories',
    title: 'Browse by Category',
    description: 'Explore our curated collections! From anime apparel to collectibles, find products that match your fandom.',
    target: '.categories, [data-categories], .category-nav',
    placement: 'bottom',
    isActive: true,
    order: 3,
    deviceType: 'both',
  },
  {
    id: 'products',
    title: 'Product Details',
    description: 'View product details, check pricing, choose variants (size, color), and read reviews from other fans.',
    target: '.product-details, [data-product], .product-info',
    placement: 'right',
    isActive: true,
    order: 4,
    deviceType: 'both',
  },
  {
    id: 'wishlist',
    title: 'Save for Later ❤️',
    description: 'Found something you love? Add it to your wishlist to save it for later. You can access your wishlist anytime from your account.',
    target: 'button[aria-label*="wishlist"], .wishlist-btn, [data-wishlist]',
    placement: 'left',
    isActive: true,
    order: 5,
    deviceType: 'both',
  },
  {
    id: 'cart',
    title: 'Your Shopping Cart',
    description: 'Review your selected items, adjust quantities, and proceed to checkout. Your cart saves everything until you\'re ready to buy.',
    target: '.cart, [data-cart], .cart-icon, [aria-label*="cart"]',
    placement: 'bottom',
    isActive: true,
    order: 6,
    deviceType: 'both',
  },
  {
    id: 'account',
    title: 'Your Account Hub',
    description: 'Manage your orders, saved addresses, profile information, and preferences all in one place.',
    target: '.account-menu, [data-account], .user-menu, [aria-label*="account"]',
    placement: 'bottom',
    isActive: true,
    order: 7,
    deviceType: 'both',
  },
  {
    id: 'checkout',
    title: 'Secure Checkout',
    description: 'Complete your purchase with our secure checkout. We support multiple payment methods including cards and mobile money.',
    target: '.checkout, [data-checkout], .checkout-btn',
    placement: 'top',
    isActive: true,
    order: 8,
    deviceType: 'both',
  },
  {
    id: 'finish',
    title: 'You\'re All Set! 🚀',
    description: 'You\'re ready to explore SpectrumCosmo! Start shopping, discover new collections, and join our community of anime fans.',
    target: 'body',
    placement: 'center',
    isActive: true,
    order: 9,
    deviceType: 'both',
  },
];

export const MOBILE_STEPS: OnboardingStep[] = DEFAULT_STEPS.map(step => ({
  ...step,
  placement: step.placement === 'right' ? 'bottom' : 
              step.placement === 'left' ? 'bottom' : 
              step.placement === 'top' ? 'bottom' : 
              step.placement,
}));
